### ISSUE TITLE
CL_INVALID_GL_SHAREGROUP_REFERENCE_KHR

### ISSUE THREAD

**Issue by c0gent** [Nopey/rust-ocl-interop#1]
So on Linux I get my usual `CL_INVALID_GL_SHAREGROUP_REFERENCE_KHR` error, which is all I ever have got when trying to do this even though my platforms and devices all have the `cl_khr_gl_sharing` extension.

I assume it's working for you on Linux so I wonder what's different about your setup.

**Comment by Nopey** [comment]
Can you try compiling this C Program I wrote? it is very similar to the `glfw_works` test. (glfw_works was based on this)
To run it, either run the shell script, or create a build directory, run cmake with the path to the base of the archive (inside cworks), run make, and then run the main executible it generates.
If this still causes the same error, we can assume it is something wrong with either your setup.
If it works, your setup is fine, and we've got a problem somewhere in the ocl-interop mix.
[cworks.zip](https://github.com/Nopey/rust-ocl-interop/files/1178492/cworks.zip)
expected result:
[image linked to save space](https://user-images.githubusercontent.com/4543739/28650717-7d5872a2-7232-11e7-8dac-75429a28e590.png)

**Comment by c0gent** [comment]
I don't have GLFW. What's the absolute quickest way to install that?

**Comment by c0gent** [comment]
Just DL source code and make some env variables?

**Comment by Nopey** [comment]
What distro are you on?

**Comment by c0gent** [comment]
Ubuntu... I didn't see it listed...

**Comment by Nopey** [comment]
Ubuntu:
```
sudo apt install libglfw3-dev
```

**Comment by Nopey** [comment]
`ubuntu-software` doesn't list all packages

**Comment by c0gent** [comment]
yeah got it, apt-get... thanks didn't see it.

**Comment by c0gent** [comment]
It's still giving me:

```
CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find GLEW (missing: GLEW_INCLUDE_DIR GLEW_LIBRARY)
```

but apparently some people are coming over in a few minutes so I've got to run. I'll fix up those env vars and test it later on.

**Comment by Nopey** [comment]
`sudo apt install libglew-dev`
sorry, forgot about that dependancy..

**Comment by c0gent** [comment]
Pesky friends gone :P

Installed that dependency (thanks). 

So now I get this, which is interesting:

```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  41
  Current serial number in output stream:  41
```

Obviously it's related. I won't spend too much time pondering on it, not just because you may have more insight than I do into it. It does make me very curious to know more.

I'll spend more time investigating if you don't have any particular insights.



##
Full `run.sh` output:

```
./run.sh 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found GLFW: /usr/include (found version "3.0.4") 
-- Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so  
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found GLEW: /usr/include  
-- Found GLX libs: /usr/lib/x86_64-linux-gnu/libGL.so
-- Found GLX includes: /usr/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nick/src/github.com/Nopey/cworks/build
Scanning dependencies of target main
Linking C executable main
[100%] Built target main
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
ret is 0 after Create Program
ret is 0 after Build Program
ret is 0 after Create Kernel
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  41
  Current serial number in output stream:  41
```

**Comment by Nopey** [comment]
What graphics card do you have, and have you installed the dev package for it? 
Mesa is attemping to use the software rasterizer for some odd reason.
I'm on NVidia and have both the dev package for my drivers (`nvidia-version-dev`) and the CUDA SDK (for OpenCL)

**Comment by c0gent** [comment]
> What graphics card do you have, and have you installed the dev package for it?

AMD 280x (2 cards) running proprietary drivers (fglrx 15.30.3 [Dec 17 2015]). I believe the AMD equivalent to a 'dev' package would be the SDK but that wouldn't have any relevance here (it's just frontends, extras, etc.).

Glium/glutin and all of my other C++ and Rust OpenGL visualization stuff runs just fine (as well as OpenGL games, etc.).

I'm guessing this is X related. I do have a slightly unusual xorg.conf just due to the fact that I have two cards, one running the display and both running OpenCL processing. Let me fiddle around with that and set a default configuration and see if it does anything.

**Comment by c0gent** [comment]
No change with everything default:

```
./run.sh 
-- Found GLX libs: /usr/lib/x86_64-linux-gnu/libGL.so
-- Found GLX includes: /usr/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nick/src/github.com/Nopey/cworks/build
[100%] Built target main
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
ret is 0 after Create Program
ret is 0 after Build Program
ret is 0 after Create Kernel
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  157 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  30
  Current serial number in output stream:  30
```

Don't waste time on this if it's something related to my configuration. I don't personally need it to work.

On the other hand if it would be useful to get to the bottom of this problem in order to progress the rest of the projects (the ocl-interop, etc.) I'm happy to do whatever I can. I have an endless patience for debugging, as I suppose we all probably do.

**Comment by Nopey** [comment]
I think the reason that it is giving you invalid sharegroup reference is because it has created the OpenGL context on one, and then ocl is presumably using the default device when creating the context, which causes it to use the other GPU. That would explain the error, and the solution would be to add a function to ocl-interop that returns the device (in cl_device form) that OpenGL is using.
Lets disregard that my c experiment didn't compile, and focus on how that function would work. I'm looking into the OpenGL side of things.

**Comment by Nopey** [comment]
https://devtalk.nvidia.com/default/topic/521379/cuda-programming-and-performance/choose-opencl-platform-and-device-corresponding-to-current-active-graphics-card/
seems relevant. bit dated, but we are working with OpenCL 1.2..

**Comment by Nopey** [comment]
Yeah okay, so we call
https://www.khronos.org/registry/OpenCL/sdk/1.1/docs/man/xhtml/clGetGLContextInfoKHR.html
with CL_DEVICES_FOR_GL_CONTEXT_KHR
and a param_value_size_ret that is the same as a single device id, so that only one device will be returned.

**Comment by Nopey** [comment]
I'm gonna open an issue over at `ocl` to get this implemented, and go to sleep.

**Comment by c0gent** [comment]
> I think the reason that it is giving you invalid sharegroup reference is because it has created the OpenGL context on one, and then ocl is presumably using the default device when creating the context, which causes it to use the other GPU. That would explain the error, and the solution would be to add a function to ocl-interop that returns the device (in cl_device form) that OpenGL is using.

I'm with you. That makes sense.

> Lets disregard that my c experiment didn't compile, and focus on how that function would work. I'm looking into the OpenGL side of things.

Well your C program compiled just fine, it just ran into some sort of OpenGL/X error (probably related to the one I'm getting in Rust-world) right? I was looking at your C code for a minute last night. I actually get further along in the process running that than I do in the Rust code. I agree it probably has something to do with platform/device selection though.

> Yeah okay, so we call https://www.khronos.org/registry/OpenCL/sdk/1.1/docs/man/xhtml/clGetGLContextInfoKHR.html
...

I totally forgot about this function. I'll hook this up sometime today :)

**Comment by c0gent** [comment]
Added  [`ocl_core::get_gl_context_info_khr`](http://docs.cogciprocate.com/ocl_core/ocl_core/fn.get_gl_context_info_khr.html),  [`GlContextInfo`](http://docs.cogciprocate.com/ocl_core/ocl_core/enum.GlContextInfo.html), and [`GlContextInfoResult`](http://docs.cogciprocate.com/ocl_core/ocl_core/types/enums/enum.GlContextInfoResult.html).

Need to test now.

**Comment by Nopey** [comment]
No way to limit the return value, but it isn't a hot function call so it doesn't really matter if it is a bit faster on optimized OpenCL implementations (I don't trust NVidia's one bit, it already screwed me out of OpenCL 2)

**Comment by Nopey** [comment]
I had an issue compiling it on my stale nightly rust, so I made the mistake of running rustup.
heres my expanded method of creating a context, that should find the cl_device that the gl context is using, and find the cl_platform that the device belongs to.
Is there a simpler way of unwrapping these Result enums? I feel like if there isn't, maybe replacing the GLContextInfoResult enum with just a Result<vec<device>> might be a worthwhile shortcut.
Honestly I don't understand the Info, InfoResult idiom thats going on with these functions.
```rust
let context;
        let properties=get_properties_list();
        match ocl::core::get_gl_context_info_khr(properties, ocl::core::GlContextInfo::CurrentDevice){
            ocl::core::GlContextInfoResult::CurrentDevice(dev)=>{
                match ocl::core::get_device_info_khr(plat, ocl::core::DeviceInfo::Platform){
                    ocl::core::DeviceInfoResult::Platform(plat)=>{
                                context=Context::builder()
                                    .properties(properties)
                                    .devices(ocl::Device::from(dev))
                                    .platform(ocl::Platform::from(plat))
                                    .build()
                                    .unwrap();
                    }
                    ocl::core::DeviceInfoResult::Error(err)=>{panic!("Unable to get CL platform to match GL device {}",err)}
                    _=>{panic!("Unexpected error")}
                }
            }
            ocl::core::GlContextInfoResult::Error(err)=>{panic!("Unable to get CL device to match GL context {}",err)}
            _=>{panic!("Unexpected error")}
        }
```

**Comment by Nopey** [comment]
I'm _still_ getting this error after updating to latest stable.
```
error: local ambiguity: multiple parsing options: built-in NTs ident ('variant') or 1 other option.
   --> /home/magnus/.cargo/git/checkouts/ocl-core-ea504f22c1693b63/d53f8fe/src/lib.rs:871:9
    |
871 |         /// Return the CL device currently associated with the specified OpenGL context.
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
rust nightly has a different error, an internal one.

**Comment by c0gent** [comment]
> No way to limit the return value, but it isn't a hot function call so it doesn't really matter if it is a bit faster on optimized OpenCL implementations

If someone needed that degree of optimization they could pretty trivially make the call to the `ffi` version of the function themselves. I've found that optimizations like that when dealing with the APIs from the three major vendors (AMD, NVIDIA, Intel) are a waste of effort. Generally, calls to the API take a very long time relative to any minor speedup one could hope to get with things like that. Plus, there really isn't any API-calling code that could really be considered 'hot' in the same way as normal CPU code would be. It's a fairly high-latency world in general.

> I had an issue compiling it on my stale nightly rust, so I made the mistake of running rustup

I had this the other day as well (an ICE). The bug report had already been filed. I've just been using the beta channel for your project.

> heres my expanded method of creating a context, that should find the cl_device that the gl context is using, and find the cl_platform that the device belongs to.

Cool, looks pretty much about what I was thinking as well.

> Is there a simpler way of unwrapping these Result enums? 

Absolutely, I was planning to add a simple method to `GlContextInfoResult` to get the device returned I just haven't had any time yet. I'll show you what I mean here soon.

> Honestly I don't understand the Info, InfoResult idiom thats going on with these functions.

This is very useful feedback. I feel the same way about these sometimes but I can't quite put my finger on what it is.

I'm certainly open to changing the design library-wide (for all of the info-result pairs). I've always felt at least a renaming was in order. I never really expected that it would be a heavily trafficked part of ocl-core, and would generally be abstracted away by some other interface in ocl and not dealt with directly (i.e. [Device::name](https://docs.rs/ocl/0.14.1/src/ocl/standard/device.rs.html#374)).

Much of the design of it is trying to be as ergonomic and simple as possible while staying as true as possible to the original naming of the original API pieces. I'd certainly welcome any ideas for how to improve any aspect of it.

> I'm still getting this error after updating to latest stable.

I suspect this is due to a difference in the NVIDIA platform software. I haven't tested anything yet so I'll play around with it on one of my machines with NVIDIA cards when I get time later this afternoon (I've been extremely busy unfortunately). It's possible that we may have to feature-gate this function.

**Comment by c0gent** [comment]
https://github.com/cogciprocate/ocl-core/commit/f69648406708f0f71854c6971385caa9977108a4

Replace 

```match ocl::core::get_gl_context_info_khr(properties, ocl::core::GlContextInfo::CurrentDevice) ...```

with 

```ocl::core::get_gl_context_info_khr(properties, ocl::core::GlContextInfo::CurrentDevice).device()```

(just call `::device`).

Once this is working and settled a bit I'll add an ocl-level interface for it so that you can also just call `Device::platform()` (I'll add that fn) on the resulting device and not have all that nested match statement business.

**Comment by c0gent** [comment]
Upon further reflection, `::device` has been changed to return an `OclResult`:

```
    /// Returns the device contained within.
    pub fn device(self) -> OclResult<DeviceId> {
        match self {
            GlContextInfoResult::CurrentDevice(d) => Ok(d),
            GlContextInfoResult::Error(err) => Err(*err),
            _ => Err("GlContextInfoResult::device: Not a 'GlContextInfoResult::Device(...)'.".into()),
        }
    }
```

I also want you to know I sympathize with you 100% that a lot of this info-result stuff results in a lot of extra code. It does. For a function like this it seems like unnecessary overkill as there are only two variants. We could simply have one function for each and be done with it. The problem is, for many of the *info functions, there are a huge number of variants and the API bloat would become pretty enormous. Furthermore, since errors already have to be dealt with by the caller anyway, there's already a branch (`match`, etc.) involved after the API call.

On a side note, a few info-calling tasks that are considered 'hot' do have their own functions such as [`event_is_complete`](https://github.com/cogciprocate/ocl-core/blob/master/src/functions.rs#L3442).

**Comment by Nopey** [comment]
I'm gonna take a break from this issue for a few days.

the real beauty of using `result`s is that lazy developers can assume theres not an error and `::unwrap`, conscious developers can ease people's debugging and `::expect`, and dedicated developers can use `match` and cover every error.

**Comment by c0gent** [comment]
Absolutely. I'll be out of town all weekend as well :)

A question for you to ponder until you return... Where exactly is your project stalled right now and what can I do to help? Answer me in a few days or so.

I'm going for a hike in the morning. Get outside and enjoy some fresh summertime air :)

**Comment by Nopey** [comment]
ocl-interop needs proper tests, that device-finding code, and maybe some small user-guide in the README.
I'm not using ocl-interop in any project, I started ocl-interop because I wanted to make a small ocl demo in rust on the GPU, and there was progress that had happened like, a week before I looked to see if it was ready. So I decided that the development was active enough for me to stick my head in and not get lost.

**Comment by c0gent** [comment]
I fixed [`get_gl_context_info_khr`](https://github.com/cogciprocate/ocl-core/blob/master/src/functions.rs#L791) so that it (correctly) uses a function pointer to call [`clGetGLContextInfoKHR`](https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/clGetGLContextInfoKHR.html) but I just can't get it to work. I fiddled around with it for a few hours or so yesterday but it it segfaults right when calling the function behind the pointer (which is not null and looks like a valid address).

I triple-checked the [function signature](https://github.com/cogciprocate/cl-sys/blob/master/src/cl_gl_h.rs#L56) and experimented with passing all sorts of different arguments (including 0/null for everything). Same result. There's something wrong with the address returned by [`clGetExtensionFunctionAddressForPlatform`](https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/clGetExtensionFunctionAddressForPlatform.html) or else there's some strange difference in the way that Rust loads or links the driver library. 

To be honest this one's beyond me. To go further I feel I'd need to delve into into the intricacies of precisely how dynamically linked libraries are loaded into memory. 

Or maybe I just made a silly mistake somewhere...

**Comment by Nopey** [comment]
I've got a method of detecting device without `get_gl_context_info_khr`, its hacky, but _"it works on my  machine"_
Attempt every possible platform/device combo with the GL Context, until one of them doesn't return a `CL_INVALID_SHAREGROUP_REFERENCE`.
This will likely fail on some implementations.
Can you test out how it works/fails on your machine?

**Comment by Nopey** [comment]
just run the `cargo test`s
GLFW, Glutin, and SDL2 will all have a turn to run.
Glutin won't display anything, I don't know why.
Each will automatically close in ~5 seconds.
I have a Glium+Glutin test, its disabled. Only works if it runs first, and then leaves its window hanging around until the program exits.

**Comment by c0gent** [comment]
Ok so first of all, I fixed the little issue with the signature of `Buffer::from_gl_buffer` so you can just use the version from the master branch and the error in your test will go away.

Second, you should remove the dependency on `glutin` and simply `use glium::glutin` within `tests/lib.rs`. I was having an issue with different versions of winit.

So finally, I've been developing on Windows lately due to driver issues with some of my GPUs. Running `cargo test` works just fine and passes but no windows are displayed. I'm now going to go through the test code and figure out what's wrong but if you can think of anything off the top of your head, let me know. 

EDIT: Correction: Only the `it_doesnt_crash` test passes. The other one one fails:
```
    Running target\debug\deps\lib-afc88d1a95a98b2f.exe
error: test failed, to rerun pass '--test lib'
```

**Comment by c0gent** [comment]
Ok, fixed an issue with one of the libraries. Test is running now. Output is:

```
C:\src\github.com\Nopey\rust-ocl-interop [master ≡ +0 ~3 -0 !]> cargo test
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target\debug\deps\ocl_interop-2cc4eb2e2dbb5f64.exe

running 1 test
test tests::it_doesnt_crash ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target\debug\deps\lib-ca3184ca88400595.exe

running 1 test
test all_works ... FAILED

failures:

---- all_works stdout ----
        Testing glfw...
PROGRAM: 1 VERTEX: 2 FRAG: 3
this line is fine 0
this line should be okay 0
this line used to get an INVALID_OPERATION error [1282]. (#0)
this line might be okay 0
thread 'all_works' panicked at 'called `Result::unwrap()` on an `Err` value:

################################ OPENCL ERROR ###############################

Error executing function: clCreateContext

Status error code: CL_INVALID_GL_SHAREGROUP_REFERENCE_KHR (-1000)

Please visit the following url for more information:

https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clCreateContext.html#errors

#############################################################################
', src\libcore\result.rs:906:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:91
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:383
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:391
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:577
   4: std::panicking::begin_panic<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:538
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:522
   6: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:498
   7: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
   8: core::result::unwrap_failed<ocl_core::error::Error>
             at C:\projects\rust\src\libcore\macros.rs:23
   9: core::result::Result<ocl::standard::context::Context, ocl_core::error::Error>::unwrap<ocl::standard::context::Context,ocl_core::error::Error>
             at C:\projects\rust\src\libcore\result.rs:772
  10: lib::{{impl}}::init
             at .\tests\lib.rs:291
  11: lib::glfw_works
             at .\tests\lib.rs:476
  12: lib::all_works
             at .\tests\lib.rs:381
  13: test::{{impl}}::call_box<(),closure>
             at C:\projects\rust\src\libtest\lib.rs:142
  14: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:101


failures:
    all_works

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test lib'
```

**Comment by Nopey** [comment]
You don't seem to be on master, line 381 is `sdl2_works`'s call, not `glfw_works` and by line 291 in glfw_works, the CL context is already created

**Comment by c0gent** [comment]
I'm on master, I just had a few println's in there. It'd be line 378 i believe. 

EDIT: Scratch that... after removing my print statements it's correctly back on line 380.

```
     Running target\debug\deps\lib-ca3184ca88400595.exe

running 1 test
test all_works ... FAILED

failures:

---- all_works stdout ----
        PROGRAM: 1 VERTEX: 2 FRAG: 3
this line is fine 0
this line should be okay 0
this line used to get an INVALID_OPERATION error [1282]. (#0)
this line might be okay 0
thread 'all_works' panicked at 'called `Result::unwrap()` on an `Err` value:

################################ OPENCL ERROR ###############################

Error executing function: clCreateContext

Status error code: CL_INVALID_GL_SHAREGROUP_REFERENCE_KHR (-1000)

Please visit the following url for more information:

https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clCreateContext.html#errors

#############################################################################
', src\libcore\result.rs:906:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:91
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:383
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:391
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:577
   4: std::panicking::begin_panic<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:538
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:522
   6: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:498
   7: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
   8: core::result::unwrap_failed<ocl_core::error::Error>
             at C:\projects\rust\src\libcore\macros.rs:23
   9: core::result::Result<ocl::standard::context::Context, ocl_core::error::Error>::unwrap<ocl::standard::context::Context,ocl_core::error::Error>
             at C:\projects\rust\src\libcore\result.rs:772
  10: lib::{{impl}}::init
             at .\tests\lib.rs:291
  11: lib::glfw_works
             at .\tests\lib.rs:473
  12: lib::all_works
             at .\tests\lib.rs:380
  13: test::{{impl}}::call_box<(),closure>
             at C:\projects\rust\src\libtest\lib.rs:142
  14: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:101


failures:
    all_works

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by Nopey** [comment]
Oops! I had written the new Device & Platform detection in the MultiplyScalar test content, but not the FillVBO (triangle) test content, which was still using the naive detection.
The MultiplyScalar test content isn't even run >_<
Try the latest master

**Comment by c0gent** [comment]
```
     Running target\debug\deps\lib-900ad777734feef6.exe

running 1 test
test all_works ... FAILED

failures:

---- all_works stdout ----
        PROGRAM: 1 VERTEX: 2 FRAG: 3
this line is fine 0
this line should be okay 0
this line used to get an INVALID_OPERATION error [1282]. (#0)
this line might be okay 0
thread 'all_works' panicked at 'Cannot find GL's device in CL', src\libcore\option.rs:874:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:91
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:383
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:391
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:577
   4: std::panicking::begin_panic<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:538
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:522
   6: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:498
   7: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
   8: core::option::expect_failed
             at C:\projects\rust\src\libcore\option.rs:874
   9: core::option::Option<core::option::Option<core::result::Result<ocl::standard::context::Context, ocl_core::error::Error>>>::expect<core::option::Option<core::result::Result<ocl::standard::context::Context, ocl_core::error::Error>>>
             at C:\projects\rust\src\libcore\option.rs:302
  10: lib::{{impl}}::init
             at .\tests\lib.rs:290
  11: lib::glfw_works
             at .\tests\lib.rs:482
  12: lib::all_works
             at .\tests\lib.rs:389
  13: test::{{impl}}::call_box<(),closure>
             at C:\projects\rust\src\libtest\lib.rs:142
  14: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:101


failures:
    all_works

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test lib'
```

**Comment by c0gent** [comment]
I'm back and forth from my desk... Ping me in this gitter channel for a quicker response:

https://gitter.im/cogciprocate/ocl

The github -> gmail -> my phone has like a 10 - 15min delay sometimes.

**Comment by c0gent** [comment]
```
     Running target\debug\deps\lib-900ad777734feef6.exe

running 1 test
test all_works ... FAILED

failures:

---- all_works stdout ----
        PROGRAM: 1 VERTEX: 2 FRAG: 3
this line is fine 0
this line should be okay 0
this line used to get an INVALID_OPERATION error [1282]. (#0)
this line might be okay 0
Plat: Platform { Profile: FULL_PROFILE, Version: OpenCL 1.2 , Name: Intel(R) OpenCL, Vendor: Intel(R) Corporation, Extensions: cl_khr_icd cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_depth_images cl_khr_3d_image_writes cl_intel_exec_by_local_thread cl_khr_spir cl_khr_dx9_media_sharing cl_intel_dx9_media_sharing cl_khr_d3d11_sharing cl_khr_fp64 }
- Dev: [] Ctx: Err(ocl::core::create_context(): No devices specified.)
Plat: Platform { Profile: FULL_PROFILE, Version: OpenCL 2.0 AMD-APP (2442.9), Name: AMD Accelerated Parallel Processing, Vendor: Advanced Micro Devices, Inc., Extensions: cl_khr_icd cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_amd_event_callback cl_amd_offline_devices  }
- Dev: [Device(DeviceId(0x2bce509e2f0)), Device(DeviceId(0x2bce50c61a0))] Ctx: Err(

################################ OPENCL ERROR ###############################

Error executing function: clCreateContext

Status error code: CL_INVALID_GL_SHAREGROUP_REFERENCE_KHR (-1000)

Please visit the following url for more information:

https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clCreateContext.html#errors

#############################################################################
)
thread 'all_works' panicked at 'Cannot find GL's device in CL', src\libcore\option.rs:874:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:91
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:383
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:391
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:577
   4: std::panicking::begin_panic<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:538
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:522
   6: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:498
   7: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
   8: core::option::expect_failed
             at C:\projects\rust\src\libcore\option.rs:874
   9: core::option::Option<core::option::Option<core::result::Result<ocl::standard::context::Context, ocl_core::error::Error>>>::expect<core::option::Option<core::result::Result<ocl::standard::context::Context, ocl_core::error::Error>>>
             at C:\projects\rust\src\libcore\option.rs:302
  10: lib::{{impl}}::init
             at .\tests\lib.rs:290
  11: lib::glfw_works
             at .\tests\lib.rs:485
  12: lib::all_works
             at .\tests\lib.rs:392
  13: test::{{impl}}::call_box<(),closure>
             at C:\projects\rust\src\libtest\lib.rs:142
  14: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:101


failures:
    all_works
```
